# Multi-Variable Linear Regression Example with Pytorch Models (다중 변수의 선형회귀)
- 국립한밭대학교 컴퓨터공학과 임경태
- https://sites.google.com/view/aailab

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_train = np.array([[2, 3, 1], 
                    [4, 8, 9], 
                    [6, 2, 7], 
                    [8, 4, 6]])
y_train = np.array([[3], 
                    [7], 
                    [5], 
                    [8]])

n_samples = x_train.shape[0]
n_features = x_train.shape[1]
losses = []

In [3]:
import torch

In [4]:
linear_model = torch.nn.Linear(in_features=3, out_features=1)       ## torch에서 제공하는 linear model 사용 (기존에는 직접 구현함)
                                                                    ## Linear 함수 소스 직접 보기
                                                                    ## in_features : 몇 개의 feature를 넣고 샆은지
                                                                    ## out_features : 몇 개의 feature를 얻고 싶은지(output)
                                                                    ## LQuiz... inear를 사용하지 않고 Fully_CoNnected Layer를 만들 때에는? linear 로 만들고 중간에 activation function을 넣어주면 FCN(ReLU)
                                                                    ## W, b는 torch 형태로 되어 있음 backward 할 때 미분값을 바로 구할 수 있음
                                                                    # instance가 출력됨 -> def forward가 실행됭

print(linear_model)
print(list(linear_model.parameters()))                              ## 첫 번째 tensor는 parmeter를 return 해서 보여줌

Linear(in_features=3, out_features=1, bias=True)
[Parameter containing:
tensor([[-0.1199,  0.1989,  0.4556]], requires_grad=True), Parameter containing:
tensor([0.4497], requires_grad=True)]


In [5]:
x_train_torch = torch.from_numpy(x_train).float()
y_train_torch = torch.from_numpy(y_train).float()
print(x_train_torch)
print(x_train_torch.shape)

tensor([[2., 3., 1.],
        [4., 8., 9.],
        [6., 2., 7.],
        [8., 4., 6.]])
torch.Size([4, 3])


In [6]:
predicted_y = linear_model(x_train_torch)                       ## 예) 수학, 과학, 영어 점수 넣어서 return 값을 predicted_y에 저장함
## predicted_y = linear_model.forward(x_train_torch)            ## linear model을 설계하고 f 함수를 forward

In [7]:
optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.01) 
loss_function = torch.nn.MSELoss()

In [8]:
linear_model.train()                                            ## linear_model.train() : 모델이 커질수록 관리할 수 없으니 내장함수인 train을 이용해서 linear 에 들어간 w,b는 업데이트 하는걸로 설정을 바꿔줌
for idx in range(100):
  optimizer.zero_grad()
  predicted_y = linear_model(x_train_torch)
  loss = loss_function(predicted_y, y_train_torch)  
  print(loss.item())
  loss.backward()
  optimizer.step()


8.113842010498047
5.4332146644592285
3.791672706604004
2.7691736221313477
2.1179513931274414
1.6914077997207642
1.4024457931518555
1.1990389823913574
1.049888014793396
0.9359879493713379
0.8456623554229736
0.7716289162635803
0.7092626094818115
0.655558168888092
0.6085152626037598
0.5667595863342285
0.5293225646018982
0.495496928691864
0.4647504985332489
0.4366716146469116
0.41093480587005615
0.3872746229171753
0.36547189950942993
0.3453405797481537
0.32672327756881714
0.30948305130004883
0.29349982738494873
0.27866822481155396
0.26489391922950745
0.25209271907806396
0.24018898606300354
0.22911369800567627
0.21880480647087097
0.2092050313949585
0.2002623975276947
0.19192931056022644
0.18416164815425873
0.1769188940525055
0.17016291618347168
0.1638604998588562
0.15797892212867737
0.1524885892868042
0.14736220240592957
0.14257416129112244
0.1381012201309204
0.1339210867881775
0.13001340627670288
0.12635931372642517
0.1229415237903595
0.11974315345287323
0.11674924194812775
0.1139457076787